version: "3.8"

services:
  web:
    build: .
    container_name: debt_management_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: :mariadb_container
    environment:
      MARIADB_DATABASE: debt_database
      MARIADB_ROOT_PASSWORD: debt_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
