openapi: "3.0.0"
info:
  title: WebDebt API
  version: "1.0"
servers:
  - url: https://localhost:8000/api/
paths:
  /member:
    get:
      summary: "メンバーを一覧で取得する"
      responses:
        "200":
          description: "成功時のレスポンス"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: "string"
                    example: "kotaro"
                  discord_id:
                    type: "string"
                    example: "960825958208765973"

    post:
      summary: "メンバーを登録する"
      description: "ログインした際に未登録の場合のみ"
      responses:
        "200":
          description: "成功時のレスポンス"
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: "string"
                    example: "kotaro"
                  discord_id:
                    type: "string"
                    example: "960825958208765973"
                  login_id:
                    type: "string"
                    example: ""
  /user_data/{code}:
    get:
      summary: "ログイン時の処理を行う"
      description: "Discordの認証後、URLのcodeの値"
      parameters:
        - name: "code"
          in: "path"
          description: "URLのcodeの値"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "ログインに成功し、Discordからユーザの情報を取得できている"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_name:
                    type: "string"
                    example: "kotaro"
                  discord_id:
                    type: "string"
                    example: "960825958208765973"
                  avatar_id:
                    type: "string"
                    example: "9776f1de158a59c811cbfe80b4425d74"
