# Generated by Django 5.1.1 on 2024-11-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("discord_id", models.CharField(max_length=100)),
                ("avatar_id", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "member_list_table",
            },
        ),
    ]
